import { Router } from "express";
import authRoutes from "./auth.js";
import complaintsRoutes from "./complaints.js";
import expensesRoutes from "./expenses.js";
import invoicesRoutes from "./invoices.js";
import jobsRoutes from "./jobs.js";
import maintenanceActivitiesRoutes from "./maintenanceActivities.js";
import maintenanceSchedulesRoutes from "./maintenanceSchedules.js";
import masterDataRoutes from "./masterData.js";
import notificationsRoutes from "./notifications.js";
import onboardingRoutes from "./onboarding.js";
import profileRoutes from "./profile.js";
import quotationsRoutes from "./quotations.js";
import reportsRoutes from "./reports.js";
import residentBillingRoutes from "./residentBilling.js";
import residentComplaintsRoutes from "./residentComplaints.js";
import residentReportsRoutes from "./residentReports.js";
import residentsRoutes from "./residents.js";
import setupRoutes from "./setup.js";
import vendorsRoutes from "./vendors.js";

const router = Router();

router.use("/auth", authRoutes);
router.use("/onboarding", onboardingRoutes);
router.use("/setup", setupRoutes);
router.use("/master-data", masterDataRoutes);
router.use("/profile", profileRoutes);
router.use("/invoices", invoicesRoutes);
router.use("/resident/complaints", residentComplaintsRoutes);
router.use("/resident/reports", residentReportsRoutes);
router.use("/resident", residentBillingRoutes);
router.use("/residents", residentsRoutes);
router.use("/complaints", complaintsRoutes);
router.use("/vendors", vendorsRoutes);
router.use("/quotations", quotationsRoutes);
router.use("/expenses", expensesRoutes);
router.use("/maintenance-activities", maintenanceActivitiesRoutes);
router.use("/maintenance-schedules", maintenanceSchedulesRoutes);
router.use("/reports", reportsRoutes);
router.use("/notifications", notificationsRoutes);
router.use("/jobs", jobsRoutes);

export default router;
